Repository nextcloud/docker-ci, pull requests merged in 2023-05, with the labels that each got.

#548 Translate "stefan-niedermann nextcloud-tables" Android app
  translations/config.json
  translations/handlePlainTranslations.sh
Labels: enhancement, transifex

#545 fix(CI): Move spreed translations as first app
  translations/config.json
  translations/transifexSync.php
Labels: transifex

#547 Remove translation job for fractava/biblio
  translations/config.json
Labels: transifex

#549 fix(transifex): Translate stable27 and drop stable24
  translations-app/handleAppTranslations.sh
  translations/handleTranslations.sh
Labels: enhancement, transifex

#550 chore: update workflows from templates
  .github/workflows/command-rebase.yml
Labels: automated, dependencies, 3. to review
