Repository nextcloud/docker-ci, pull requests merged in 2023-11, with the labels that each got.

#434 feat(memcached): Add memcached service
  memcached/Dockerfile
Labels: enhancement, 3. to review

#433 feat(redis)!: Use Alpine base
  redis/Dockerfile
Labels: enhancement, 3. to review

#600 chore: Drop recipes with unsupported - outdated - PHP versions
  ftp-php7.0/Dockerfile
  ftp-php7.0/launch
  ftp-php7.0/proftpd.conf
  integration-php7.0/Dockerfile
  litmus-php7.0/Dockerfile
  mysql-5.7/Dockerfile
  php5.4/Dockerfile
  php5.4/nextcloud.ini
  php5.5/Dockerfile
  php5.5/nextcloud.ini
  php5.6/Dockerfile
  php5.6/nextcloud.ini
  php7.0-memcached/Dockerfile
  php7.0-memcached/nextcloud.ini
  php7.0/Dockerfile
  php7.0/nextcloud.ini
  samba-native-php7.0/Dockerfile
  samba-native-php7.0/smbclient.ini
  samba-non-native-php7.0/Dockerfile
  samba-non-native-php7.0/smb.conf
  webdav-apache-php7.0/Dockerfile
  webdav-apache-php7.0/webdav.conf
Labels: 3. to review

#606 fix(l10n): Adjust translated branches
  translations-app/handleAppTranslations.sh
  translations/handleTranslations.sh
Labels: enhancement, transifex

#613 fix(translations): Use main/master branch app description for transl…
  translations-app/handleAppTranslations.sh
  translations/handleTranslations.sh
Labels: bug, transifex
