Repository nextcloud/docker-ci, pull requests merged in 2025-01, with the labels that each got.

#702 fix(appstore): Remove ug translation from appstore as it regularly br…
  translations/handleAppstoreTranslations.sh
Labels: bug, transifex

#706 fix(translationtool): Fallback to English plural form
  translations/translationtool/src/translationtool.php
  translations/translationtool/translationtool.phar
Labels: bug, transifex, 3. to review

#718 Increased threshold for translations of iOS apps
  translations/handleiOSNotesTranslations.sh
  translations/handleiOSTranslations.sh
Labels: enhancement
